### ISSUE TITLE
Implement Selection Sort

### ISSUE THREAD

**Issue by arielroque** [arielroque/Sortanejo#6]
Add explanation and code for Selection Sort algorithm

**Comment by Vinitvh** [comment]
Hi @arielroque, can I implement this?

**Comment by arielroque** [comment]
Sorry for the delay @Vinitvh :(. Can you select another one? I just realized now a pull request from someone for this exact implementation.

**Comment by arielroque** [comment]
I will fix this issue because @ignaciolight8 already send a pull request to this implementation.

**Comment by Vinitvh** [comment]
No issues. Will pick another one.
